.\" Manpage for stepgrampa
.\" Contact andrew@rail5.org to correct errors or typos.
.TH man 8 "27 December 2022" "1.0" "stepgrampa man page"
.SH NAME
stepgrampa
.SH SYNOPSIS
stepgrampa
.SH DESCRIPTION
stepgrampa replaces MATE's engrampa with GNOME's file-roller for use in caja
The command "engrampa" will simply forward to "file-roller" and pass along all arguments
This package also provides the "caja extension" for use in right-click context menus
.SH AUTHOR
rail5 (andrew@rail5.org)
